[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clipboard = {path = "../clipboard"}
core_lib = {path = "../core", package = "core"}
zbus = "5.2"
tokio = { version = "1.43", features = ["full"] }
global-hotkey = "0.6"
serde_json = "1.0"